// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/interrogatory_model.dart';
import 'models/personal_data_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 3996157001370866902),
      name: 'Elemento',
      lastPropertyId: const obx_int.IdUid(4, 2789899094985484205),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 4620656507009253317),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 8313944828278512612),
            name: 'seccionId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(1, 8355460756985994122),
            relationTarget: 'Seccion'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 8192819360287344475),
            name: 'nombre',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 2789899094985484205),
            name: 'respuesta',
            type: 1,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 2039920815618038356),
      name: 'Interrogatorio',
      lastPropertyId: const obx_int.IdUid(2, 288244551746073971),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 3283002862773472693),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 288244551746073971),
            name: 'pacienteId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(2, 502127217175195618),
            relationTarget: 'Paciente')
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[
        obx_int.ModelBacklink(
            name: 'secciones', srcEntity: 'Seccion', srcField: 'interrogatorio')
      ]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(3, 6473606377810914912),
      name: 'Seccion',
      lastPropertyId: const obx_int.IdUid(4, 4736388164980832843),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 7004613500463965696),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 4031979108904179218),
            name: 'interrogatorioId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(3, 8615709609684153934),
            relationTarget: 'Interrogatorio'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 1041392091051900192),
            name: 'nombre',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 4736388164980832843),
            name: 'observaciones',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[
        obx_int.ModelBacklink(
            name: 'elementos', srcEntity: 'Elemento', srcField: 'seccion')
      ]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(4, 8411594303202627597),
      name: 'Antecedente',
      lastPropertyId: const obx_int.IdUid(5, 2397559045123795297),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 3816908882025309547),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 6946298700383009072),
            name: 'pacienteId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(4, 7217166825669020857),
            relationTarget: 'Paciente'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 6099677868881949995),
            name: 'tipo',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 8725841013314236900),
            name: 'descripcion',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 2397559045123795297),
            name: 'fecha',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(5, 7066300506379273094),
      name: 'AntecedentesGinecologicos',
      lastPropertyId: const obx_int.IdUid(15, 7579944251982521369),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 6873006406621804689),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 1131702034902472903),
            name: 'pacienteId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(5, 4673826886208878337),
            relationTarget: 'Paciente'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 5573122592414387848),
            name: 'edadMenopausia',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 15578828889677499),
            name: 'caracteristicasMenopausia',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 2886368570308582740),
            name: 'edadMenarquia',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 8939444700213158009),
            name: 'caracteristicasMenarquia',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 3129004696033345760),
            name: 'edadPrimeraRelacion',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 1833224210884899908),
            name: 'formulaMenstrual',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 6307867125477447838),
            name: 'fechaUltimaMenstruacion',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 8109860552178038901),
            name: 'tipoMenstruacion',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 4319897323573016060),
            name: 'fechaUltimoUso',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 6071069589358863920),
            name: 'descripcion',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(13, 3282540669822285510),
            name: 'barrera',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(14, 7565772058390091562),
            name: 'diu',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(15, 7579944251982521369),
            name: 'hormonales',
            type: 1,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[
        obx_int.ModelRelation(
            id: const obx_int.IdUid(3, 6772359203914994911),
            name: 'resultadosCitologicos',
            targetId: const obx_int.IdUid(8, 481877359317515240))
      ],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(6, 1657572938707936780),
      name: 'AntecedentesObstetricos',
      lastPropertyId: const obx_int.IdUid(2, 2569798145263887908),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 1417413020368612841),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 2569798145263887908),
            name: 'pacienteId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(6, 8764369305178925836),
            relationTarget: 'Paciente')
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[
        obx_int.ModelBacklink(
            name: 'embarazos', srcEntity: 'Embarazo', srcField: 'antecedente')
      ]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(7, 4114459817740905263),
      name: 'AntecedentesPatologicosPersonales',
      lastPropertyId: const obx_int.IdUid(2, 7796862840842859515),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 4447891385762171544),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 7796862840842859515),
            name: 'pacienteId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(7, 3353095543676520960),
            relationTarget: 'Paciente')
      ],
      relations: <obx_int.ModelRelation>[
        obx_int.ModelRelation(
            id: const obx_int.IdUid(4, 5374108844642427757),
            name: 'enfermedadesGenerales',
            targetId: const obx_int.IdUid(11, 7089720316066374324)),
        obx_int.ModelRelation(
            id: const obx_int.IdUid(5, 8976206580456137568),
            name: 'enfermedadesEndocrinas',
            targetId: const obx_int.IdUid(11, 7089720316066374324)),
        obx_int.ModelRelation(
            id: const obx_int.IdUid(6, 3132579534341660856),
            name: 'enfermedadesRespiratorias',
            targetId: const obx_int.IdUid(11, 7089720316066374324)),
        obx_int.ModelRelation(
            id: const obx_int.IdUid(7, 9001800775513223439),
            name: 'enfermedadesCardiovasculares',
            targetId: const obx_int.IdUid(11, 7089720316066374324)),
        obx_int.ModelRelation(
            id: const obx_int.IdUid(8, 4406262932103991477),
            name: 'enfermedadesDigestivas',
            targetId: const obx_int.IdUid(11, 7089720316066374324)),
        obx_int.ModelRelation(
            id: const obx_int.IdUid(9, 2379681043930324469),
            name: 'enfermedadesRenales',
            targetId: const obx_int.IdUid(11, 7089720316066374324)),
        obx_int.ModelRelation(
            id: const obx_int.IdUid(10, 341265251135044910),
            name: 'enfermedadesNeuronales',
            targetId: const obx_int.IdUid(11, 7089720316066374324)),
        obx_int.ModelRelation(
            id: const obx_int.IdUid(11, 9021303638898101427),
            name: 'enfermedadesHematologicas',
            targetId: const obx_int.IdUid(11, 7089720316066374324)),
        obx_int.ModelRelation(
            id: const obx_int.IdUid(12, 4865565211692369094),
            name: 'enfermedadesReumatologicas',
            targetId: const obx_int.IdUid(11, 7089720316066374324)),
        obx_int.ModelRelation(
            id: const obx_int.IdUid(13, 8511458797484966722),
            name: 'enfermedadesTransmisionSexual',
            targetId: const obx_int.IdUid(11, 7089720316066374324)),
        obx_int.ModelRelation(
            id: const obx_int.IdUid(14, 5431265603138581775),
            name: 'enfermedadesGinecologicas',
            targetId: const obx_int.IdUid(11, 7089720316066374324))
      ],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(8, 481877359317515240),
      name: 'Citologia',
      lastPropertyId: const obx_int.IdUid(6, 3899959400123138690),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 5678424343420424006),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 7071589064601155813),
            name: 'fecha',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 5999243117047418902),
            name: 'resultado',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 3081777977847942952),
            name: 'fueraDePrograma',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 3033260751448151741),
            name: 'observaciones',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 3899959400123138690),
            name: 'antecedenteId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(8, 1564196683658499304),
            relationTarget: 'AntecedentesGinecologicos')
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(9, 8963735491338825201),
      name: 'Embarazo',
      lastPropertyId: const obx_int.IdUid(10, 4553939452853934538),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 4976000982870638274),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 284637894532176300),
            name: 'numeroEmbarazo',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 4135647763745377932),
            name: 'fecha',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 6156727314404464043),
            name: 'semanasGestacion',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 4924597020371366633),
            name: 'abortoEtiologia',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 8742371177842350079),
            name: 'caracteristicasNacimiento',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 2033068620117086852),
            name: 'tipoParto',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 3706295933325343478),
            name: 'tipoDistocia',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 8675331509041243062),
            name: 'lugarParto',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 4553939452853934538),
            name: 'antecedenteId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(9, 4952087313181750900),
            relationTarget: 'AntecedentesObstetricos')
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[
        obx_int.ModelBacklink(
            name: 'recienNacidos',
            srcEntity: 'RecienNacido',
            srcField: 'embarazo')
      ]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(10, 6994753854429315169),
      name: 'EmbarazoActual',
      lastPropertyId: const obx_int.IdUid(8, 2480313616167909595),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 2289473705598561201),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 269903087541201097),
            name: 'fechaUltimaMenstruacion',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 5485375319852938880),
            name: 'noConfiable',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 976892871061360406),
            name: 'desconocida',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 7396322892749590010),
            name: 'fechaPartoEstimado',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 8226083003854369966),
            name: 'captacion',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 3145088494317739303),
            name: 'semanas',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 2480313616167909595),
            name: 'pacienteId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(10, 2224098582144887869),
            relationTarget: 'Paciente')
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(11, 7089720316066374324),
      name: 'Enfermedad',
      lastPropertyId: const obx_int.IdUid(6, 8340623301015607575),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 5861855200996886656),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 3723269846334473281),
            name: 'nombre',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 5017688750439591039),
            name: 'cronica',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 336772267005165871),
            name: 'fecha',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 70286265651357390),
            name: 'descripcion',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 8340623301015607575),
            name: 'antecedenteId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(11, 6150895150813013170),
            relationTarget: 'AntecedentesPatologicosPersonales')
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(12, 7761614205288077719),
      name: 'Paciente',
      lastPropertyId: const obx_int.IdUid(31, 5355125049851457999),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 6645908137672119143),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 4153934984931940090),
            name: 'nombre',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 4138903358659998831),
            name: 'primerApellido',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 6809138812501845439),
            name: 'segundoApellido',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 7010769336451265829),
            name: 'fechaNacimiento',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 1437902931996693737),
            name: 'sexo',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 8250619644147972432),
            name: 'direccion',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 386823849339154268),
            name: 'tipoDePaciente',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 6590517229691698969),
            name: 'noIdentidad',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 6731300692350944303),
            name: 'aboRh',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 3292015507542328778),
            name: 'unidadHospitalaria',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 255427572119228785),
            name: 'policlinico',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(13, 391294667442635865),
            name: 'estadoCivil',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(14, 3798317399516846472),
            name: 'escolaridad',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(15, 3753449852418223487),
            name: 'consultorio',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(16, 421399869648070139),
            name: 'ocupacion',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(17, 31519700120712879),
            name: 'noDormitorios',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(18, 8566665016071885249),
            name: 'noPersonasNucleoPersonal',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(19, 6505066405161352395),
            name: 'tipoDeRiesgo',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(20, 756456543361609068),
            name: 'datosDeInteres',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(21, 5828903731586805718),
            name: 'tipoDeDiagnostico',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(22, 3867419837382740067),
            name: 'codigo',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(23, 7235565564391156028),
            name: 'descripcion',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(24, 4716319074072869736),
            name: 'estructura',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(25, 2245632216575404706),
            name: 'conductaSeguida',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(26, 8396832012455940696),
            name: 'antecedentesPatologicosId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(12, 8057303325378860992),
            relationTarget: 'AntecedentesPatologicosPersonales'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(27, 1315203403585535857),
            name: 'antecedentesObstetricosId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(13, 3360524346302828976),
            relationTarget: 'AntecedentesObstetricos'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(28, 5779527745294701656),
            name: 'embarazoActualId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(14, 3417801690771563341),
            relationTarget: 'EmbarazoActual'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(29, 8733439380872150914),
            name: 'interrogatorioId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(15, 4300594980004109624),
            relationTarget: 'Interrogatorio'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(30, 9126572931702301462),
            name: 'fechaDeRegistro',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(31, 5355125049851457999),
            name: 'fechaDeActualizacion',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[
        obx_int.ModelBacklink(
            name: 'antecedentes',
            srcEntity: 'Antecedente',
            srcField: 'paciente')
      ]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(13, 6960418874851669987),
      name: 'RecienNacido',
      lastPropertyId: const obx_int.IdUid(10, 2906726004146979595),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 7976672240331173612),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 3824656945508566701),
            name: 'peso',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 1929070064626367316),
            name: 'sexo',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 6559535105552477417),
            name: 'estado',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 9544660455389653),
            name: 'datosInteres',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 6244678276833832486),
            name: 'apgar',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 2850486851874379276),
            name: 'puntos',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 3188294265347618620),
            name: 'ocurrenciaDefuncion',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 2734800343283078170),
            name: 'edadAlFallecer',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 2906726004146979595),
            name: 'embarazoId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(16, 3429999169993845107),
            relationTarget: 'Embarazo')
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(13, 6960418874851669987),
      lastIndexId: const obx_int.IdUid(16, 3429999169993845107),
      lastRelationId: const obx_int.IdUid(14, 5431265603138581775),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [737123734785742008, 5549541683541151137],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    Elemento: obx_int.EntityDefinition<Elemento>(
        model: _entities[0],
        toOneRelations: (Elemento object) => [object.seccion],
        toManyRelations: (Elemento object) => {},
        getId: (Elemento object) => object.id,
        setId: (Elemento object, int id) {
          object.id = id;
        },
        objectToFB: (Elemento object, fb.Builder fbb) {
          final nombreOffset = fbb.writeString(object.nombre);
          fbb.startTable(5);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.seccion.targetId);
          fbb.addOffset(2, nombreOffset);
          fbb.addBool(3, object.respuesta);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final nombreParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final object = Elemento(id: idParam, nombre: nombreParam)
            ..respuesta =
                const fb.BoolReader().vTableGetNullable(buffer, rootOffset, 10);
          object.seccion.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          object.seccion.attach(store);
          return object;
        }),
    Interrogatorio: obx_int.EntityDefinition<Interrogatorio>(
        model: _entities[1],
        toOneRelations: (Interrogatorio object) => [object.paciente],
        toManyRelations: (Interrogatorio object) => {
              obx_int.RelInfo<Seccion>.toOneBacklink(2, object.id,
                      (Seccion srcObject) => srcObject.interrogatorio):
                  object.secciones
            },
        getId: (Interrogatorio object) => object.id,
        setId: (Interrogatorio object, int id) {
          object.id = id;
        },
        objectToFB: (Interrogatorio object, fb.Builder fbb) {
          fbb.startTable(3);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.paciente.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final object = Interrogatorio(id: idParam);
          object.paciente.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          object.paciente.attach(store);
          obx_int.InternalToManyAccess.setRelInfo<Interrogatorio>(
              object.secciones,
              store,
              obx_int.RelInfo<Seccion>.toOneBacklink(2, object.id,
                  (Seccion srcObject) => srcObject.interrogatorio));
          return object;
        }),
    Seccion: obx_int.EntityDefinition<Seccion>(
        model: _entities[2],
        toOneRelations: (Seccion object) => [object.interrogatorio],
        toManyRelations: (Seccion object) => {
              obx_int.RelInfo<Elemento>.toOneBacklink(
                      2, object.id, (Elemento srcObject) => srcObject.seccion):
                  object.elementos
            },
        getId: (Seccion object) => object.id,
        setId: (Seccion object, int id) {
          object.id = id;
        },
        objectToFB: (Seccion object, fb.Builder fbb) {
          final nombreOffset = fbb.writeString(object.nombre);
          final observacionesOffset = object.observaciones == null
              ? null
              : fbb.writeString(object.observaciones!);
          fbb.startTable(5);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.interrogatorio.targetId);
          fbb.addOffset(2, nombreOffset);
          fbb.addOffset(3, observacionesOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final nombreParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final object = Seccion(id: idParam, nombre: nombreParam)
            ..observaciones = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 10);
          object.interrogatorio.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          object.interrogatorio.attach(store);
          obx_int.InternalToManyAccess.setRelInfo<Seccion>(
              object.elementos,
              store,
              obx_int.RelInfo<Elemento>.toOneBacklink(
                  2, object.id, (Elemento srcObject) => srcObject.seccion));
          return object;
        }),
    Antecedente: obx_int.EntityDefinition<Antecedente>(
        model: _entities[3],
        toOneRelations: (Antecedente object) => [object.paciente],
        toManyRelations: (Antecedente object) => {},
        getId: (Antecedente object) => object.id,
        setId: (Antecedente object, int id) {
          object.id = id;
        },
        objectToFB: (Antecedente object, fb.Builder fbb) {
          final tipoOffset = fbb.writeString(object.tipo);
          final descripcionOffset = fbb.writeString(object.descripcion);
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.paciente.targetId);
          fbb.addOffset(2, tipoOffset);
          fbb.addOffset(3, descripcionOffset);
          fbb.addInt64(4, object.fecha?.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final fechaValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 12);
          final tipoParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final descripcionParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, '');
          final fechaParam = fechaValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(fechaValue);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final object =
              Antecedente(tipoParam, descripcionParam, fechaParam, id: idParam);
          object.paciente.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          object.paciente.attach(store);
          return object;
        }),
    AntecedentesGinecologicos: obx_int.EntityDefinition<
            AntecedentesGinecologicos>(
        model: _entities[4],
        toOneRelations: (AntecedentesGinecologicos object) => [object.paciente],
        toManyRelations: (AntecedentesGinecologicos object) => {
              obx_int.RelInfo<AntecedentesGinecologicos>.toMany(3, object.id):
                  object.resultadosCitologicos
            },
        getId: (AntecedentesGinecologicos object) => object.id,
        setId: (AntecedentesGinecologicos object, int id) {
          object.id = id;
        },
        objectToFB: (AntecedentesGinecologicos object, fb.Builder fbb) {
          final caracteristicasMenopausiaOffset =
              object.caracteristicasMenopausia == null
                  ? null
                  : fbb.writeString(object.caracteristicasMenopausia!);
          final caracteristicasMenarquiaOffset =
              object.caracteristicasMenarquia == null
                  ? null
                  : fbb.writeString(object.caracteristicasMenarquia!);
          final formulaMenstrualOffset = object.formulaMenstrual == null
              ? null
              : fbb.writeString(object.formulaMenstrual!);
          final tipoMenstruacionOffset = object.tipoMenstruacion == null
              ? null
              : fbb.writeString(object.tipoMenstruacion!);
          final descripcionOffset = object.descripcion == null
              ? null
              : fbb.writeString(object.descripcion!);
          fbb.startTable(16);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.paciente.targetId);
          fbb.addInt64(2, object.edadMenopausia);
          fbb.addOffset(3, caracteristicasMenopausiaOffset);
          fbb.addInt64(4, object.edadMenarquia);
          fbb.addOffset(5, caracteristicasMenarquiaOffset);
          fbb.addInt64(6, object.edadPrimeraRelacion);
          fbb.addOffset(7, formulaMenstrualOffset);
          fbb.addInt64(
              8, object.fechaUltimaMenstruacion?.millisecondsSinceEpoch);
          fbb.addOffset(9, tipoMenstruacionOffset);
          fbb.addInt64(10, object.fechaUltimoUso?.millisecondsSinceEpoch);
          fbb.addOffset(11, descripcionOffset);
          fbb.addBool(12, object.barrera);
          fbb.addBool(13, object.diu);
          fbb.addBool(14, object.hormonales);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final fechaUltimaMenstruacionValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 20);
          final fechaUltimoUsoValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 24);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final object = AntecedentesGinecologicos(id: idParam)
            ..edadMenopausia =
                const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 8)
            ..caracteristicasMenopausia =
                const fb.StringReader(asciiOptimization: true)
                    .vTableGetNullable(buffer, rootOffset, 10)
            ..edadMenarquia =
                const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 12)
            ..caracteristicasMenarquia =
                const fb.StringReader(asciiOptimization: true)
                    .vTableGetNullable(buffer, rootOffset, 14)
            ..edadPrimeraRelacion =
                const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 16)
            ..formulaMenstrual = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 18)
            ..fechaUltimaMenstruacion = fechaUltimaMenstruacionValue == null
                ? null
                : DateTime.fromMillisecondsSinceEpoch(
                    fechaUltimaMenstruacionValue)
            ..tipoMenstruacion = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 22)
            ..fechaUltimoUso = fechaUltimoUsoValue == null
                ? null
                : DateTime.fromMillisecondsSinceEpoch(fechaUltimoUsoValue)
            ..descripcion = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 26)
            ..barrera =
                const fb.BoolReader().vTableGetNullable(buffer, rootOffset, 28)
            ..diu =
                const fb.BoolReader().vTableGetNullable(buffer, rootOffset, 30)
            ..hormonales =
                const fb.BoolReader().vTableGetNullable(buffer, rootOffset, 32);
          object.paciente.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          object.paciente.attach(store);
          obx_int.InternalToManyAccess.setRelInfo<AntecedentesGinecologicos>(
              object.resultadosCitologicos,
              store,
              obx_int.RelInfo<AntecedentesGinecologicos>.toMany(3, object.id));
          return object;
        }),
    AntecedentesObstetricos: obx_int.EntityDefinition<AntecedentesObstetricos>(
        model: _entities[5],
        toOneRelations: (AntecedentesObstetricos object) => [object.paciente],
        toManyRelations: (AntecedentesObstetricos object) => {
              obx_int.RelInfo<Embarazo>.toOneBacklink(10, object.id,
                      (Embarazo srcObject) => srcObject.antecedente):
                  object.embarazos
            },
        getId: (AntecedentesObstetricos object) => object.id,
        setId: (AntecedentesObstetricos object, int id) {
          object.id = id;
        },
        objectToFB: (AntecedentesObstetricos object, fb.Builder fbb) {
          fbb.startTable(3);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.paciente.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final object = AntecedentesObstetricos(id: idParam);
          object.paciente.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          object.paciente.attach(store);
          obx_int.InternalToManyAccess.setRelInfo<AntecedentesObstetricos>(
              object.embarazos,
              store,
              obx_int.RelInfo<Embarazo>.toOneBacklink(10, object.id,
                  (Embarazo srcObject) => srcObject.antecedente));
          return object;
        }),
    AntecedentesPatologicosPersonales:
        obx_int.EntityDefinition<AntecedentesPatologicosPersonales>(
            model: _entities[6],
            toOneRelations: (AntecedentesPatologicosPersonales object) =>
                [object.paciente],
            toManyRelations: (AntecedentesPatologicosPersonales object) => {
                  obx_int.RelInfo<AntecedentesPatologicosPersonales>.toMany(
                      4, object.id): object.enfermedadesGenerales,
                  obx_int.RelInfo<AntecedentesPatologicosPersonales>.toMany(
                      5, object.id): object.enfermedadesEndocrinas,
                  obx_int.RelInfo<AntecedentesPatologicosPersonales>.toMany(
                      6, object.id): object.enfermedadesRespiratorias,
                  obx_int.RelInfo<AntecedentesPatologicosPersonales>.toMany(
                      7, object.id): object.enfermedadesCardiovasculares,
                  obx_int.RelInfo<AntecedentesPatologicosPersonales>.toMany(
                      8, object.id): object.enfermedadesDigestivas,
                  obx_int.RelInfo<AntecedentesPatologicosPersonales>.toMany(
                      9, object.id): object.enfermedadesRenales,
                  obx_int.RelInfo<AntecedentesPatologicosPersonales>.toMany(
                      10, object.id): object.enfermedadesNeuronales,
                  obx_int.RelInfo<AntecedentesPatologicosPersonales>.toMany(
                      11, object.id): object.enfermedadesHematologicas,
                  obx_int.RelInfo<AntecedentesPatologicosPersonales>.toMany(
                      12, object.id): object.enfermedadesReumatologicas,
                  obx_int.RelInfo<AntecedentesPatologicosPersonales>.toMany(
                      13, object.id): object.enfermedadesTransmisionSexual,
                  obx_int.RelInfo<AntecedentesPatologicosPersonales>.toMany(
                      14, object.id): object.enfermedadesGinecologicas
                },
            getId: (AntecedentesPatologicosPersonales object) => object.id,
            setId: (AntecedentesPatologicosPersonales object, int id) {
              object.id = id;
            },
            objectToFB:
                (AntecedentesPatologicosPersonales object, fb.Builder fbb) {
              fbb.startTable(3);
              fbb.addInt64(0, object.id);
              fbb.addInt64(1, object.paciente.targetId);
              fbb.finish(fbb.endTable());
              return object.id;
            },
            objectFromFB: (obx.Store store, ByteData fbData) {
              final buffer = fb.BufferContext(fbData);
              final rootOffset = buffer.derefObject(0);
              final idParam =
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
              final object = AntecedentesPatologicosPersonales(id: idParam);
              object.paciente.targetId =
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
              object.paciente.attach(store);
              obx_int.InternalToManyAccess.setRelInfo<
                      AntecedentesPatologicosPersonales>(
                  object.enfermedadesGenerales,
                  store,
                  obx_int.RelInfo<AntecedentesPatologicosPersonales>.toMany(
                      4, object.id));
              obx_int.InternalToManyAccess.setRelInfo<
                      AntecedentesPatologicosPersonales>(
                  object.enfermedadesEndocrinas,
                  store,
                  obx_int.RelInfo<AntecedentesPatologicosPersonales>.toMany(
                      5, object.id));
              obx_int.InternalToManyAccess.setRelInfo<
                      AntecedentesPatologicosPersonales>(
                  object.enfermedadesRespiratorias,
                  store,
                  obx_int.RelInfo<AntecedentesPatologicosPersonales>.toMany(
                      6, object.id));
              obx_int.InternalToManyAccess.setRelInfo<
                      AntecedentesPatologicosPersonales>(
                  object.enfermedadesCardiovasculares,
                  store,
                  obx_int.RelInfo<AntecedentesPatologicosPersonales>.toMany(
                      7, object.id));
              obx_int.InternalToManyAccess.setRelInfo<
                      AntecedentesPatologicosPersonales>(
                  object.enfermedadesDigestivas,
                  store,
                  obx_int.RelInfo<AntecedentesPatologicosPersonales>.toMany(
                      8, object.id));
              obx_int.InternalToManyAccess.setRelInfo<
                      AntecedentesPatologicosPersonales>(
                  object.enfermedadesRenales,
                  store,
                  obx_int.RelInfo<AntecedentesPatologicosPersonales>.toMany(
                      9, object.id));
              obx_int.InternalToManyAccess.setRelInfo<
                      AntecedentesPatologicosPersonales>(
                  object.enfermedadesNeuronales,
                  store,
                  obx_int.RelInfo<AntecedentesPatologicosPersonales>.toMany(
                      10, object.id));
              obx_int.InternalToManyAccess.setRelInfo<
                      AntecedentesPatologicosPersonales>(
                  object.enfermedadesHematologicas,
                  store,
                  obx_int.RelInfo<AntecedentesPatologicosPersonales>.toMany(
                      11, object.id));
              obx_int.InternalToManyAccess.setRelInfo<
                      AntecedentesPatologicosPersonales>(
                  object.enfermedadesReumatologicas,
                  store,
                  obx_int.RelInfo<AntecedentesPatologicosPersonales>.toMany(
                      12, object.id));
              obx_int.InternalToManyAccess.setRelInfo<
                      AntecedentesPatologicosPersonales>(
                  object.enfermedadesTransmisionSexual,
                  store,
                  obx_int.RelInfo<AntecedentesPatologicosPersonales>.toMany(
                      13, object.id));
              obx_int.InternalToManyAccess.setRelInfo<
                      AntecedentesPatologicosPersonales>(
                  object.enfermedadesGinecologicas,
                  store,
                  obx_int.RelInfo<AntecedentesPatologicosPersonales>.toMany(
                      14, object.id));
              return object;
            }),
    Citologia: obx_int.EntityDefinition<Citologia>(
        model: _entities[7],
        toOneRelations: (Citologia object) => [object.antecedente],
        toManyRelations: (Citologia object) => {},
        getId: (Citologia object) => object.id,
        setId: (Citologia object, int id) {
          object.id = id;
        },
        objectToFB: (Citologia object, fb.Builder fbb) {
          final resultadoOffset = fbb.writeString(object.resultado);
          final observacionesOffset = object.observaciones == null
              ? null
              : fbb.writeString(object.observaciones!);
          fbb.startTable(7);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.fecha.millisecondsSinceEpoch);
          fbb.addOffset(2, resultadoOffset);
          fbb.addBool(3, object.fueraDePrograma);
          fbb.addOffset(4, observacionesOffset);
          fbb.addInt64(5, object.antecedente.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final fechaParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0));
          final resultadoParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final fueraDeProgramaParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 10, false);
          final observacionesParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 12);
          final object = Citologia(
              id: idParam,
              fecha: fechaParam,
              resultado: resultadoParam,
              fueraDePrograma: fueraDeProgramaParam,
              observaciones: observacionesParam);
          object.antecedente.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0);
          object.antecedente.attach(store);
          return object;
        }),
    Embarazo: obx_int.EntityDefinition<Embarazo>(
        model: _entities[8],
        toOneRelations: (Embarazo object) => [object.antecedente],
        toManyRelations: (Embarazo object) => {
              obx_int.RelInfo<RecienNacido>.toOneBacklink(10, object.id,
                      (RecienNacido srcObject) => srcObject.embarazo):
                  object.recienNacidos
            },
        getId: (Embarazo object) => object.id,
        setId: (Embarazo object, int id) {
          object.id = id;
        },
        objectToFB: (Embarazo object, fb.Builder fbb) {
          final abortoEtiologiaOffset = object.abortoEtiologia == null
              ? null
              : fbb.writeString(object.abortoEtiologia!);
          final caracteristicasNacimientoOffset =
              fbb.writeString(object.caracteristicasNacimiento);
          final tipoPartoOffset = fbb.writeString(object.tipoParto);
          final tipoDistociaOffset = fbb.writeString(object.tipoDistocia);
          final lugarPartoOffset = fbb.writeString(object.lugarParto);
          fbb.startTable(11);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.numeroEmbarazo);
          fbb.addInt64(2, object.fecha.millisecondsSinceEpoch);
          fbb.addInt64(3, object.semanasGestacion);
          fbb.addOffset(4, abortoEtiologiaOffset);
          fbb.addOffset(5, caracteristicasNacimientoOffset);
          fbb.addOffset(6, tipoPartoOffset);
          fbb.addOffset(7, tipoDistociaOffset);
          fbb.addOffset(8, lugarPartoOffset);
          fbb.addInt64(9, object.antecedente.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final numeroEmbarazoParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          final fechaParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0));
          final semanasGestacionParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final abortoEtiologiaParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 12);
          final caracteristicasNacimientoParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 14, '');
          final tipoPartoParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 16, '');
          final tipoDistociaParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 18, '');
          final lugarPartoParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 20, '');
          final object = Embarazo(
              id: idParam,
              numeroEmbarazo: numeroEmbarazoParam,
              fecha: fechaParam,
              semanasGestacion: semanasGestacionParam,
              abortoEtiologia: abortoEtiologiaParam,
              caracteristicasNacimiento: caracteristicasNacimientoParam,
              tipoParto: tipoPartoParam,
              tipoDistocia: tipoDistociaParam,
              lugarParto: lugarPartoParam);
          object.antecedente.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0);
          object.antecedente.attach(store);
          obx_int.InternalToManyAccess.setRelInfo<Embarazo>(
              object.recienNacidos,
              store,
              obx_int.RelInfo<RecienNacido>.toOneBacklink(10, object.id,
                  (RecienNacido srcObject) => srcObject.embarazo));
          return object;
        }),
    EmbarazoActual: obx_int.EntityDefinition<EmbarazoActual>(
        model: _entities[9],
        toOneRelations: (EmbarazoActual object) => [object.paciente],
        toManyRelations: (EmbarazoActual object) => {},
        getId: (EmbarazoActual object) => object.id,
        setId: (EmbarazoActual object, int id) {
          object.id = id;
        },
        objectToFB: (EmbarazoActual object, fb.Builder fbb) {
          fbb.startTable(9);
          fbb.addInt64(0, object.id);
          fbb.addInt64(
              1, object.fechaUltimaMenstruacion?.millisecondsSinceEpoch);
          fbb.addBool(2, object.noConfiable);
          fbb.addBool(3, object.desconocida);
          fbb.addInt64(4, object.fechaPartoEstimado?.millisecondsSinceEpoch);
          fbb.addInt64(5, object.captacion);
          fbb.addInt64(6, object.semanas);
          fbb.addInt64(7, object.paciente.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final fechaUltimaMenstruacionValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 6);
          final fechaPartoEstimadoValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 12);
          final fechaUltimaMenstruacionParam =
              fechaUltimaMenstruacionValue == null
                  ? null
                  : DateTime.fromMillisecondsSinceEpoch(
                      fechaUltimaMenstruacionValue);
          final noConfiableParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 8, false);
          final desconocidaParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 10, false);
          final fechaPartoEstimadoParam = fechaPartoEstimadoValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(fechaPartoEstimadoValue);
          final captacionParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0);
          final semanasParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final object = EmbarazoActual(
              fechaUltimaMenstruacionParam,
              noConfiableParam,
              desconocidaParam,
              fechaPartoEstimadoParam,
              captacionParam,
              semanasParam,
              id: idParam);
          object.paciente.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0);
          object.paciente.attach(store);
          return object;
        }),
    Enfermedad: obx_int.EntityDefinition<Enfermedad>(
        model: _entities[10],
        toOneRelations: (Enfermedad object) => [object.antecedente],
        toManyRelations: (Enfermedad object) => {},
        getId: (Enfermedad object) => object.id,
        setId: (Enfermedad object, int id) {
          object.id = id;
        },
        objectToFB: (Enfermedad object, fb.Builder fbb) {
          final nombreOffset = fbb.writeString(object.nombre);
          final descripcionOffset = fbb.writeString(object.descripcion);
          fbb.startTable(7);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nombreOffset);
          fbb.addBool(2, object.cronica);
          fbb.addInt64(3, object.fecha?.millisecondsSinceEpoch);
          fbb.addOffset(4, descripcionOffset);
          fbb.addInt64(5, object.antecedente.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final fechaValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 10);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final nombreParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final cronicaParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 8, false);
          final fechaParam = fechaValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(fechaValue);
          final descripcionParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 12, '');
          final object = Enfermedad(
              id: idParam,
              nombre: nombreParam,
              cronica: cronicaParam,
              fecha: fechaParam,
              descripcion: descripcionParam);
          object.antecedente.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0);
          object.antecedente.attach(store);
          return object;
        }),
    Paciente: obx_int.EntityDefinition<Paciente>(
        model: _entities[11],
        toOneRelations: (Paciente object) => [
              object.antecedentesPatologicos,
              object.antecedentesObstetricos,
              object.embarazoActual,
              object.interrogatorio
            ],
        toManyRelations: (Paciente object) => {
              obx_int.RelInfo<Antecedente>.toOneBacklink(2, object.id,
                      (Antecedente srcObject) => srcObject.paciente):
                  object.antecedentes
            },
        getId: (Paciente object) => object.id,
        setId: (Paciente object, int id) {
          object.id = id;
        },
        objectToFB: (Paciente object, fb.Builder fbb) {
          final nombreOffset = fbb.writeString(object.nombre);
          final primerApellidoOffset = fbb.writeString(object.primerApellido);
          final segundoApellidoOffset = fbb.writeString(object.segundoApellido);
          final sexoOffset = fbb.writeString(object.sexo);
          final direccionOffset = fbb.writeString(object.direccion);
          final tipoDePacienteOffset = fbb.writeString(object.tipoDePaciente);
          final noIdentidadOffset = fbb.writeString(object.noIdentidad);
          final aboRhOffset = fbb.writeString(object.aboRh);
          final unidadHospitalariaOffset =
              fbb.writeString(object.unidadHospitalaria);
          final policlinicoOffset = fbb.writeString(object.policlinico);
          final estadoCivilOffset = fbb.writeString(object.estadoCivil);
          final escolaridadOffset = fbb.writeString(object.escolaridad);
          final consultorioOffset = fbb.writeString(object.consultorio);
          final ocupacionOffset = fbb.writeString(object.ocupacion);
          final tipoDeRiesgoOffset = fbb.writeString(object.tipoDeRiesgo);
          final datosDeInteresOffset = fbb.writeString(object.datosDeInteres);
          final tipoDeDiagnosticoOffset =
              fbb.writeString(object.tipoDeDiagnostico);
          final codigoOffset = fbb.writeString(object.codigo);
          final descripcionOffset = fbb.writeString(object.descripcion);
          final estructuraOffset = fbb.writeString(object.estructura);
          final conductaSeguidaOffset = fbb.writeString(object.conductaSeguida);
          fbb.startTable(32);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nombreOffset);
          fbb.addOffset(2, primerApellidoOffset);
          fbb.addOffset(3, segundoApellidoOffset);
          fbb.addInt64(4, object.fechaNacimiento.millisecondsSinceEpoch);
          fbb.addOffset(5, sexoOffset);
          fbb.addOffset(6, direccionOffset);
          fbb.addOffset(7, tipoDePacienteOffset);
          fbb.addOffset(8, noIdentidadOffset);
          fbb.addOffset(9, aboRhOffset);
          fbb.addOffset(10, unidadHospitalariaOffset);
          fbb.addOffset(11, policlinicoOffset);
          fbb.addOffset(12, estadoCivilOffset);
          fbb.addOffset(13, escolaridadOffset);
          fbb.addOffset(14, consultorioOffset);
          fbb.addOffset(15, ocupacionOffset);
          fbb.addInt64(16, object.noDormitorios);
          fbb.addInt64(17, object.noPersonasNucleoPersonal);
          fbb.addOffset(18, tipoDeRiesgoOffset);
          fbb.addOffset(19, datosDeInteresOffset);
          fbb.addOffset(20, tipoDeDiagnosticoOffset);
          fbb.addOffset(21, codigoOffset);
          fbb.addOffset(22, descripcionOffset);
          fbb.addOffset(23, estructuraOffset);
          fbb.addOffset(24, conductaSeguidaOffset);
          fbb.addInt64(25, object.antecedentesPatologicos.targetId);
          fbb.addInt64(26, object.antecedentesObstetricos.targetId);
          fbb.addInt64(27, object.embarazoActual.targetId);
          fbb.addInt64(28, object.interrogatorio.targetId);
          fbb.addInt64(29, object.fechaDeRegistro.millisecondsSinceEpoch);
          fbb.addInt64(30, object.fechaDeActualizacion.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final nombreParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final primerApellidoParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, '');
          final segundoApellidoParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, '');
          final fechaNacimientoParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0));
          final sexoParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 14, '');
          final direccionParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 16, '');
          final tipoDePacienteParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 18, '');
          final noIdentidadParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 20, '');
          final aboRhParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 22, '');
          final unidadHospitalariaParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 24, '');
          final policlinicoParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 26, '');
          final estadoCivilParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 28, '');
          final escolaridadParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 30, '');
          final consultorioParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 32, '');
          final ocupacionParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 34, '');
          final noDormitoriosParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 36, 0);
          final noPersonasNucleoPersonalParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 38, 0);
          final codigoParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 46, '');
          final datosDeInteresParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 42, '');
          final descripcionParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 48, '');
          final estructuraParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 50, '');
          final tipoDeDiagnosticoParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 44, '');
          final tipoDeRiesgoParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 40, '');
          final conductaSeguidaParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 52, '');
          final fechaDeRegistroParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 62, 0));
          final fechaDeActualizacionParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 64, 0));
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final object = Paciente(
              nombreParam,
              primerApellidoParam,
              segundoApellidoParam,
              fechaNacimientoParam,
              sexoParam,
              direccionParam,
              tipoDePacienteParam,
              noIdentidadParam,
              aboRhParam,
              unidadHospitalariaParam,
              policlinicoParam,
              estadoCivilParam,
              escolaridadParam,
              consultorioParam,
              ocupacionParam,
              noDormitoriosParam,
              noPersonasNucleoPersonalParam,
              codigoParam,
              datosDeInteresParam,
              descripcionParam,
              estructuraParam,
              tipoDeDiagnosticoParam,
              tipoDeRiesgoParam,
              conductaSeguidaParam,
              fechaDeRegistroParam,
              fechaDeActualizacionParam,
              id: idParam);
          object.antecedentesPatologicos.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 54, 0);
          object.antecedentesPatologicos.attach(store);
          object.antecedentesObstetricos.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 56, 0);
          object.antecedentesObstetricos.attach(store);
          object.embarazoActual.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 58, 0);
          object.embarazoActual.attach(store);
          object.interrogatorio.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 60, 0);
          object.interrogatorio.attach(store);
          obx_int.InternalToManyAccess.setRelInfo<Paciente>(
              object.antecedentes,
              store,
              obx_int.RelInfo<Antecedente>.toOneBacklink(
                  2, object.id, (Antecedente srcObject) => srcObject.paciente));
          return object;
        }),
    RecienNacido: obx_int.EntityDefinition<RecienNacido>(
        model: _entities[12],
        toOneRelations: (RecienNacido object) => [object.embarazo],
        toManyRelations: (RecienNacido object) => {},
        getId: (RecienNacido object) => object.id,
        setId: (RecienNacido object, int id) {
          object.id = id;
        },
        objectToFB: (RecienNacido object, fb.Builder fbb) {
          final sexoOffset = fbb.writeString(object.sexo);
          final estadoOffset = fbb.writeString(object.estado);
          final datosInteresOffset = object.datosInteres == null
              ? null
              : fbb.writeString(object.datosInteres!);
          final ocurrenciaDefuncionOffset = object.ocurrenciaDefuncion == null
              ? null
              : fbb.writeString(object.ocurrenciaDefuncion!);
          final edadAlFallecerOffset = object.edadAlFallecer == null
              ? null
              : fbb.writeString(object.edadAlFallecer!);
          fbb.startTable(11);
          fbb.addInt64(0, object.id);
          fbb.addFloat64(1, object.peso);
          fbb.addOffset(2, sexoOffset);
          fbb.addOffset(3, estadoOffset);
          fbb.addOffset(4, datosInteresOffset);
          fbb.addInt64(5, object.apgar);
          fbb.addInt64(6, object.puntos);
          fbb.addOffset(7, ocurrenciaDefuncionOffset);
          fbb.addOffset(8, edadAlFallecerOffset);
          fbb.addInt64(9, object.embarazo.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final pesoParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 6, 0);
          final sexoParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final estadoParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final datosInteresParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 12);
          final apgarParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0);
          final puntosParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0);
          final object = RecienNacido(
              id: idParam,
              peso: pesoParam,
              sexo: sexoParam,
              estado: estadoParam,
              datosInteres: datosInteresParam,
              apgar: apgarParam,
              puntos: puntosParam)
            ..ocurrenciaDefuncion =
                const fb.StringReader(asciiOptimization: true)
                    .vTableGetNullable(buffer, rootOffset, 18)
            ..edadAlFallecer = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 20);
          object.embarazo.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0);
          object.embarazo.attach(store);
          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Elemento] entity fields to define ObjectBox queries.
class Elemento_ {
  /// See [Elemento.id].
  static final id =
      obx.QueryIntegerProperty<Elemento>(_entities[0].properties[0]);

  /// See [Elemento.seccion].
  static final seccion =
      obx.QueryRelationToOne<Elemento, Seccion>(_entities[0].properties[1]);

  /// See [Elemento.nombre].
  static final nombre =
      obx.QueryStringProperty<Elemento>(_entities[0].properties[2]);

  /// See [Elemento.respuesta].
  static final respuesta =
      obx.QueryBooleanProperty<Elemento>(_entities[0].properties[3]);
}

/// [Interrogatorio] entity fields to define ObjectBox queries.
class Interrogatorio_ {
  /// See [Interrogatorio.id].
  static final id =
      obx.QueryIntegerProperty<Interrogatorio>(_entities[1].properties[0]);

  /// See [Interrogatorio.paciente].
  static final paciente = obx.QueryRelationToOne<Interrogatorio, Paciente>(
      _entities[1].properties[1]);

  /// see [Interrogatorio.secciones]
  static final secciones =
      obx.QueryBacklinkToMany<Seccion, Interrogatorio>(Seccion_.interrogatorio);
}

/// [Seccion] entity fields to define ObjectBox queries.
class Seccion_ {
  /// See [Seccion.id].
  static final id =
      obx.QueryIntegerProperty<Seccion>(_entities[2].properties[0]);

  /// See [Seccion.interrogatorio].
  static final interrogatorio = obx.QueryRelationToOne<Seccion, Interrogatorio>(
      _entities[2].properties[1]);

  /// See [Seccion.nombre].
  static final nombre =
      obx.QueryStringProperty<Seccion>(_entities[2].properties[2]);

  /// See [Seccion.observaciones].
  static final observaciones =
      obx.QueryStringProperty<Seccion>(_entities[2].properties[3]);

  /// see [Seccion.elementos]
  static final elementos =
      obx.QueryBacklinkToMany<Elemento, Seccion>(Elemento_.seccion);
}

/// [Antecedente] entity fields to define ObjectBox queries.
class Antecedente_ {
  /// See [Antecedente.id].
  static final id =
      obx.QueryIntegerProperty<Antecedente>(_entities[3].properties[0]);

  /// See [Antecedente.paciente].
  static final paciente =
      obx.QueryRelationToOne<Antecedente, Paciente>(_entities[3].properties[1]);

  /// See [Antecedente.tipo].
  static final tipo =
      obx.QueryStringProperty<Antecedente>(_entities[3].properties[2]);

  /// See [Antecedente.descripcion].
  static final descripcion =
      obx.QueryStringProperty<Antecedente>(_entities[3].properties[3]);

  /// See [Antecedente.fecha].
  static final fecha =
      obx.QueryDateProperty<Antecedente>(_entities[3].properties[4]);
}

/// [AntecedentesGinecologicos] entity fields to define ObjectBox queries.
class AntecedentesGinecologicos_ {
  /// See [AntecedentesGinecologicos.id].
  static final id = obx.QueryIntegerProperty<AntecedentesGinecologicos>(
      _entities[4].properties[0]);

  /// See [AntecedentesGinecologicos.paciente].
  static final paciente =
      obx.QueryRelationToOne<AntecedentesGinecologicos, Paciente>(
          _entities[4].properties[1]);

  /// See [AntecedentesGinecologicos.edadMenopausia].
  static final edadMenopausia =
      obx.QueryIntegerProperty<AntecedentesGinecologicos>(
          _entities[4].properties[2]);

  /// See [AntecedentesGinecologicos.caracteristicasMenopausia].
  static final caracteristicasMenopausia =
      obx.QueryStringProperty<AntecedentesGinecologicos>(
          _entities[4].properties[3]);

  /// See [AntecedentesGinecologicos.edadMenarquia].
  static final edadMenarquia =
      obx.QueryIntegerProperty<AntecedentesGinecologicos>(
          _entities[4].properties[4]);

  /// See [AntecedentesGinecologicos.caracteristicasMenarquia].
  static final caracteristicasMenarquia =
      obx.QueryStringProperty<AntecedentesGinecologicos>(
          _entities[4].properties[5]);

  /// See [AntecedentesGinecologicos.edadPrimeraRelacion].
  static final edadPrimeraRelacion =
      obx.QueryIntegerProperty<AntecedentesGinecologicos>(
          _entities[4].properties[6]);

  /// See [AntecedentesGinecologicos.formulaMenstrual].
  static final formulaMenstrual =
      obx.QueryStringProperty<AntecedentesGinecologicos>(
          _entities[4].properties[7]);

  /// See [AntecedentesGinecologicos.fechaUltimaMenstruacion].
  static final fechaUltimaMenstruacion =
      obx.QueryDateProperty<AntecedentesGinecologicos>(
          _entities[4].properties[8]);

  /// See [AntecedentesGinecologicos.tipoMenstruacion].
  static final tipoMenstruacion =
      obx.QueryStringProperty<AntecedentesGinecologicos>(
          _entities[4].properties[9]);

  /// See [AntecedentesGinecologicos.fechaUltimoUso].
  static final fechaUltimoUso =
      obx.QueryDateProperty<AntecedentesGinecologicos>(
          _entities[4].properties[10]);

  /// See [AntecedentesGinecologicos.descripcion].
  static final descripcion = obx.QueryStringProperty<AntecedentesGinecologicos>(
      _entities[4].properties[11]);

  /// See [AntecedentesGinecologicos.barrera].
  static final barrera = obx.QueryBooleanProperty<AntecedentesGinecologicos>(
      _entities[4].properties[12]);

  /// See [AntecedentesGinecologicos.diu].
  static final diu = obx.QueryBooleanProperty<AntecedentesGinecologicos>(
      _entities[4].properties[13]);

  /// See [AntecedentesGinecologicos.hormonales].
  static final hormonales = obx.QueryBooleanProperty<AntecedentesGinecologicos>(
      _entities[4].properties[14]);

  /// see [AntecedentesGinecologicos.resultadosCitologicos]
  static final resultadosCitologicos =
      obx.QueryRelationToMany<AntecedentesGinecologicos, Citologia>(
          _entities[4].relations[0]);
}

/// [AntecedentesObstetricos] entity fields to define ObjectBox queries.
class AntecedentesObstetricos_ {
  /// See [AntecedentesObstetricos.id].
  static final id = obx.QueryIntegerProperty<AntecedentesObstetricos>(
      _entities[5].properties[0]);

  /// See [AntecedentesObstetricos.paciente].
  static final paciente =
      obx.QueryRelationToOne<AntecedentesObstetricos, Paciente>(
          _entities[5].properties[1]);

  /// see [AntecedentesObstetricos.embarazos]
  static final embarazos =
      obx.QueryBacklinkToMany<Embarazo, AntecedentesObstetricos>(
          Embarazo_.antecedente);
}

/// [AntecedentesPatologicosPersonales] entity fields to define ObjectBox queries.
class AntecedentesPatologicosPersonales_ {
  /// See [AntecedentesPatologicosPersonales.id].
  static final id = obx.QueryIntegerProperty<AntecedentesPatologicosPersonales>(
      _entities[6].properties[0]);

  /// See [AntecedentesPatologicosPersonales.paciente].
  static final paciente =
      obx.QueryRelationToOne<AntecedentesPatologicosPersonales, Paciente>(
          _entities[6].properties[1]);

  /// see [AntecedentesPatologicosPersonales.enfermedadesGenerales]
  static final enfermedadesGenerales =
      obx.QueryRelationToMany<AntecedentesPatologicosPersonales, Enfermedad>(
          _entities[6].relations[0]);

  /// see [AntecedentesPatologicosPersonales.enfermedadesEndocrinas]
  static final enfermedadesEndocrinas =
      obx.QueryRelationToMany<AntecedentesPatologicosPersonales, Enfermedad>(
          _entities[6].relations[1]);

  /// see [AntecedentesPatologicosPersonales.enfermedadesRespiratorias]
  static final enfermedadesRespiratorias =
      obx.QueryRelationToMany<AntecedentesPatologicosPersonales, Enfermedad>(
          _entities[6].relations[2]);

  /// see [AntecedentesPatologicosPersonales.enfermedadesCardiovasculares]
  static final enfermedadesCardiovasculares =
      obx.QueryRelationToMany<AntecedentesPatologicosPersonales, Enfermedad>(
          _entities[6].relations[3]);

  /// see [AntecedentesPatologicosPersonales.enfermedadesDigestivas]
  static final enfermedadesDigestivas =
      obx.QueryRelationToMany<AntecedentesPatologicosPersonales, Enfermedad>(
          _entities[6].relations[4]);

  /// see [AntecedentesPatologicosPersonales.enfermedadesRenales]
  static final enfermedadesRenales =
      obx.QueryRelationToMany<AntecedentesPatologicosPersonales, Enfermedad>(
          _entities[6].relations[5]);

  /// see [AntecedentesPatologicosPersonales.enfermedadesNeuronales]
  static final enfermedadesNeuronales =
      obx.QueryRelationToMany<AntecedentesPatologicosPersonales, Enfermedad>(
          _entities[6].relations[6]);

  /// see [AntecedentesPatologicosPersonales.enfermedadesHematologicas]
  static final enfermedadesHematologicas =
      obx.QueryRelationToMany<AntecedentesPatologicosPersonales, Enfermedad>(
          _entities[6].relations[7]);

  /// see [AntecedentesPatologicosPersonales.enfermedadesReumatologicas]
  static final enfermedadesReumatologicas =
      obx.QueryRelationToMany<AntecedentesPatologicosPersonales, Enfermedad>(
          _entities[6].relations[8]);

  /// see [AntecedentesPatologicosPersonales.enfermedadesTransmisionSexual]
  static final enfermedadesTransmisionSexual =
      obx.QueryRelationToMany<AntecedentesPatologicosPersonales, Enfermedad>(
          _entities[6].relations[9]);

  /// see [AntecedentesPatologicosPersonales.enfermedadesGinecologicas]
  static final enfermedadesGinecologicas =
      obx.QueryRelationToMany<AntecedentesPatologicosPersonales, Enfermedad>(
          _entities[6].relations[10]);
}

/// [Citologia] entity fields to define ObjectBox queries.
class Citologia_ {
  /// See [Citologia.id].
  static final id =
      obx.QueryIntegerProperty<Citologia>(_entities[7].properties[0]);

  /// See [Citologia.fecha].
  static final fecha =
      obx.QueryDateProperty<Citologia>(_entities[7].properties[1]);

  /// See [Citologia.resultado].
  static final resultado =
      obx.QueryStringProperty<Citologia>(_entities[7].properties[2]);

  /// See [Citologia.fueraDePrograma].
  static final fueraDePrograma =
      obx.QueryBooleanProperty<Citologia>(_entities[7].properties[3]);

  /// See [Citologia.observaciones].
  static final observaciones =
      obx.QueryStringProperty<Citologia>(_entities[7].properties[4]);

  /// See [Citologia.antecedente].
  static final antecedente =
      obx.QueryRelationToOne<Citologia, AntecedentesGinecologicos>(
          _entities[7].properties[5]);
}

/// [Embarazo] entity fields to define ObjectBox queries.
class Embarazo_ {
  /// See [Embarazo.id].
  static final id =
      obx.QueryIntegerProperty<Embarazo>(_entities[8].properties[0]);

  /// See [Embarazo.numeroEmbarazo].
  static final numeroEmbarazo =
      obx.QueryIntegerProperty<Embarazo>(_entities[8].properties[1]);

  /// See [Embarazo.fecha].
  static final fecha =
      obx.QueryDateProperty<Embarazo>(_entities[8].properties[2]);

  /// See [Embarazo.semanasGestacion].
  static final semanasGestacion =
      obx.QueryIntegerProperty<Embarazo>(_entities[8].properties[3]);

  /// See [Embarazo.abortoEtiologia].
  static final abortoEtiologia =
      obx.QueryStringProperty<Embarazo>(_entities[8].properties[4]);

  /// See [Embarazo.caracteristicasNacimiento].
  static final caracteristicasNacimiento =
      obx.QueryStringProperty<Embarazo>(_entities[8].properties[5]);

  /// See [Embarazo.tipoParto].
  static final tipoParto =
      obx.QueryStringProperty<Embarazo>(_entities[8].properties[6]);

  /// See [Embarazo.tipoDistocia].
  static final tipoDistocia =
      obx.QueryStringProperty<Embarazo>(_entities[8].properties[7]);

  /// See [Embarazo.lugarParto].
  static final lugarParto =
      obx.QueryStringProperty<Embarazo>(_entities[8].properties[8]);

  /// See [Embarazo.antecedente].
  static final antecedente =
      obx.QueryRelationToOne<Embarazo, AntecedentesObstetricos>(
          _entities[8].properties[9]);

  /// see [Embarazo.recienNacidos]
  static final recienNacidos =
      obx.QueryBacklinkToMany<RecienNacido, Embarazo>(RecienNacido_.embarazo);
}

/// [EmbarazoActual] entity fields to define ObjectBox queries.
class EmbarazoActual_ {
  /// See [EmbarazoActual.id].
  static final id =
      obx.QueryIntegerProperty<EmbarazoActual>(_entities[9].properties[0]);

  /// See [EmbarazoActual.fechaUltimaMenstruacion].
  static final fechaUltimaMenstruacion =
      obx.QueryDateProperty<EmbarazoActual>(_entities[9].properties[1]);

  /// See [EmbarazoActual.noConfiable].
  static final noConfiable =
      obx.QueryBooleanProperty<EmbarazoActual>(_entities[9].properties[2]);

  /// See [EmbarazoActual.desconocida].
  static final desconocida =
      obx.QueryBooleanProperty<EmbarazoActual>(_entities[9].properties[3]);

  /// See [EmbarazoActual.fechaPartoEstimado].
  static final fechaPartoEstimado =
      obx.QueryDateProperty<EmbarazoActual>(_entities[9].properties[4]);

  /// See [EmbarazoActual.captacion].
  static final captacion =
      obx.QueryIntegerProperty<EmbarazoActual>(_entities[9].properties[5]);

  /// See [EmbarazoActual.semanas].
  static final semanas =
      obx.QueryIntegerProperty<EmbarazoActual>(_entities[9].properties[6]);

  /// See [EmbarazoActual.paciente].
  static final paciente = obx.QueryRelationToOne<EmbarazoActual, Paciente>(
      _entities[9].properties[7]);
}

/// [Enfermedad] entity fields to define ObjectBox queries.
class Enfermedad_ {
  /// See [Enfermedad.id].
  static final id =
      obx.QueryIntegerProperty<Enfermedad>(_entities[10].properties[0]);

  /// See [Enfermedad.nombre].
  static final nombre =
      obx.QueryStringProperty<Enfermedad>(_entities[10].properties[1]);

  /// See [Enfermedad.cronica].
  static final cronica =
      obx.QueryBooleanProperty<Enfermedad>(_entities[10].properties[2]);

  /// See [Enfermedad.fecha].
  static final fecha =
      obx.QueryDateProperty<Enfermedad>(_entities[10].properties[3]);

  /// See [Enfermedad.descripcion].
  static final descripcion =
      obx.QueryStringProperty<Enfermedad>(_entities[10].properties[4]);

  /// See [Enfermedad.antecedente].
  static final antecedente =
      obx.QueryRelationToOne<Enfermedad, AntecedentesPatologicosPersonales>(
          _entities[10].properties[5]);
}

/// [Paciente] entity fields to define ObjectBox queries.
class Paciente_ {
  /// See [Paciente.id].
  static final id =
      obx.QueryIntegerProperty<Paciente>(_entities[11].properties[0]);

  /// See [Paciente.nombre].
  static final nombre =
      obx.QueryStringProperty<Paciente>(_entities[11].properties[1]);

  /// See [Paciente.primerApellido].
  static final primerApellido =
      obx.QueryStringProperty<Paciente>(_entities[11].properties[2]);

  /// See [Paciente.segundoApellido].
  static final segundoApellido =
      obx.QueryStringProperty<Paciente>(_entities[11].properties[3]);

  /// See [Paciente.fechaNacimiento].
  static final fechaNacimiento =
      obx.QueryDateProperty<Paciente>(_entities[11].properties[4]);

  /// See [Paciente.sexo].
  static final sexo =
      obx.QueryStringProperty<Paciente>(_entities[11].properties[5]);

  /// See [Paciente.direccion].
  static final direccion =
      obx.QueryStringProperty<Paciente>(_entities[11].properties[6]);

  /// See [Paciente.tipoDePaciente].
  static final tipoDePaciente =
      obx.QueryStringProperty<Paciente>(_entities[11].properties[7]);

  /// See [Paciente.noIdentidad].
  static final noIdentidad =
      obx.QueryStringProperty<Paciente>(_entities[11].properties[8]);

  /// See [Paciente.aboRh].
  static final aboRh =
      obx.QueryStringProperty<Paciente>(_entities[11].properties[9]);

  /// See [Paciente.unidadHospitalaria].
  static final unidadHospitalaria =
      obx.QueryStringProperty<Paciente>(_entities[11].properties[10]);

  /// See [Paciente.policlinico].
  static final policlinico =
      obx.QueryStringProperty<Paciente>(_entities[11].properties[11]);

  /// See [Paciente.estadoCivil].
  static final estadoCivil =
      obx.QueryStringProperty<Paciente>(_entities[11].properties[12]);

  /// See [Paciente.escolaridad].
  static final escolaridad =
      obx.QueryStringProperty<Paciente>(_entities[11].properties[13]);

  /// See [Paciente.consultorio].
  static final consultorio =
      obx.QueryStringProperty<Paciente>(_entities[11].properties[14]);

  /// See [Paciente.ocupacion].
  static final ocupacion =
      obx.QueryStringProperty<Paciente>(_entities[11].properties[15]);

  /// See [Paciente.noDormitorios].
  static final noDormitorios =
      obx.QueryIntegerProperty<Paciente>(_entities[11].properties[16]);

  /// See [Paciente.noPersonasNucleoPersonal].
  static final noPersonasNucleoPersonal =
      obx.QueryIntegerProperty<Paciente>(_entities[11].properties[17]);

  /// See [Paciente.tipoDeRiesgo].
  static final tipoDeRiesgo =
      obx.QueryStringProperty<Paciente>(_entities[11].properties[18]);

  /// See [Paciente.datosDeInteres].
  static final datosDeInteres =
      obx.QueryStringProperty<Paciente>(_entities[11].properties[19]);

  /// See [Paciente.tipoDeDiagnostico].
  static final tipoDeDiagnostico =
      obx.QueryStringProperty<Paciente>(_entities[11].properties[20]);

  /// See [Paciente.codigo].
  static final codigo =
      obx.QueryStringProperty<Paciente>(_entities[11].properties[21]);

  /// See [Paciente.descripcion].
  static final descripcion =
      obx.QueryStringProperty<Paciente>(_entities[11].properties[22]);

  /// See [Paciente.estructura].
  static final estructura =
      obx.QueryStringProperty<Paciente>(_entities[11].properties[23]);

  /// See [Paciente.conductaSeguida].
  static final conductaSeguida =
      obx.QueryStringProperty<Paciente>(_entities[11].properties[24]);

  /// See [Paciente.antecedentesPatologicos].
  static final antecedentesPatologicos =
      obx.QueryRelationToOne<Paciente, AntecedentesPatologicosPersonales>(
          _entities[11].properties[25]);

  /// See [Paciente.antecedentesObstetricos].
  static final antecedentesObstetricos =
      obx.QueryRelationToOne<Paciente, AntecedentesObstetricos>(
          _entities[11].properties[26]);

  /// See [Paciente.embarazoActual].
  static final embarazoActual =
      obx.QueryRelationToOne<Paciente, EmbarazoActual>(
          _entities[11].properties[27]);

  /// See [Paciente.interrogatorio].
  static final interrogatorio =
      obx.QueryRelationToOne<Paciente, Interrogatorio>(
          _entities[11].properties[28]);

  /// See [Paciente.fechaDeRegistro].
  static final fechaDeRegistro =
      obx.QueryDateProperty<Paciente>(_entities[11].properties[29]);

  /// See [Paciente.fechaDeActualizacion].
  static final fechaDeActualizacion =
      obx.QueryDateProperty<Paciente>(_entities[11].properties[30]);

  /// see [Paciente.antecedentes]
  static final antecedentes =
      obx.QueryBacklinkToMany<Antecedente, Paciente>(Antecedente_.paciente);
}

/// [RecienNacido] entity fields to define ObjectBox queries.
class RecienNacido_ {
  /// See [RecienNacido.id].
  static final id =
      obx.QueryIntegerProperty<RecienNacido>(_entities[12].properties[0]);

  /// See [RecienNacido.peso].
  static final peso =
      obx.QueryDoubleProperty<RecienNacido>(_entities[12].properties[1]);

  /// See [RecienNacido.sexo].
  static final sexo =
      obx.QueryStringProperty<RecienNacido>(_entities[12].properties[2]);

  /// See [RecienNacido.estado].
  static final estado =
      obx.QueryStringProperty<RecienNacido>(_entities[12].properties[3]);

  /// See [RecienNacido.datosInteres].
  static final datosInteres =
      obx.QueryStringProperty<RecienNacido>(_entities[12].properties[4]);

  /// See [RecienNacido.apgar].
  static final apgar =
      obx.QueryIntegerProperty<RecienNacido>(_entities[12].properties[5]);

  /// See [RecienNacido.puntos].
  static final puntos =
      obx.QueryIntegerProperty<RecienNacido>(_entities[12].properties[6]);

  /// See [RecienNacido.ocurrenciaDefuncion].
  static final ocurrenciaDefuncion =
      obx.QueryStringProperty<RecienNacido>(_entities[12].properties[7]);

  /// See [RecienNacido.edadAlFallecer].
  static final edadAlFallecer =
      obx.QueryStringProperty<RecienNacido>(_entities[12].properties[8]);

  /// See [RecienNacido.embarazo].
  static final embarazo = obx.QueryRelationToOne<RecienNacido, Embarazo>(
      _entities[12].properties[9]);
}
